name: TestTask

on:
  push:
    paths:
    - '**.yml'

jobs:
  build:

    runs-on: windows-latest
    
    steps:
    
    - name: LogAllEnv
      run: set
      
    - uses: actions/checkout@v1
    
    - name: QueryUnrealVersion
      run : |
        dir "C:/Program Files (x86)/Epic Games"
        Ue4editor-CMD.exe -server -log
